\documentclass{article}

\usepackage[portrait, headheight = 0cm, margin=0.25cm, top = 0.25cm, nofoot]{geometry} 
\usepackage[export]{adjustbox} 
\usepackage{graphicx}
\usepackage[dvipsnames,table]{xcolor} % [dvipsnames,table] for setting colors \usepackage{amsmath} \usepackage{xfrac}
\usepackage{tikz}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{shapes.misc}
%\usetikzlibrary{external}
%\tikzexternalize % activate!
%\usepackage{sparklines}
\usepackage{xfrac}

\DeclareRobustCommand\Tstrut{\rule{0pt}{2.6ex}}         % = `top' strut
\DeclareRobustCommand\Bstrut{\rule[-0.9ex]{0pt}{0pt}}   % = `bottom' strut
\renewcommand{\familydefault}{\sfdefault}

<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
require(Hmisc)
require(Rtsne)
require(digest)
require(stringi)
require(readxl)
require(scales)
require(data.table)
require(Matrix)
require(Matrix.utils)
require(clue)
require(magick)
source("utility_functions.R")
source("sheet_utility_functions.R")
source("latex_helpers_v2.R")

tikz_plot_nodes<-function(df,units="mm"){
  coordinates<-paste0("(",
    stri_trim(format(df$x,scientific=FALSE)),units,
    ",",
    stri_trim(format(df$y,scientific=FALSE)),units,
  ")")
  nodes<-paste0(coordinates," ","node","{",df$text,"}",sep="")
  path<-paste("\\path",paste0(nodes,collapse=" "),";")
  paste0("\\tikz{",path,"}\n")
}

tikz_plot_matrix<-function(m,xscale=c(0,200),yscale=c(0,200),units="mm"){
  df<-data.table(
    x=rescale(as.vector(col(m)),xscale),
    y=rescale(as.vector(row(m)),yscale),
    text=as.vector(m)
  )
  tikz_plot_nodes(df)
}

df<-data.table(
  x=round(runif(100,0,200),digits=0),
  y=round(runif(100,0,200),digits=0),
  text=paste0("s",1:100)
)



images<-fread("images.csv")

icon<-function(pair,height="3cm",width="3cm"){
  images[,.SD,keyby=name][pair,paste0("\\includegraphics[height=",height,",width=",width,",valign=T]{",file,"}")]
}

pair_layout<-data.table(
  x=round(runif(100,0,200),digits=0),
  y=round(runif(100,0,200),digits=0),
  text=paste("\\fbox{",icon(images$name,height="15mm",width="12mm"),"}")
)

#tikz_plot_matrix(df2matrix(pair_layout))

@

\begin{document}

\begin{center}
\resizebox{20cm}{20cm}{\Sexpr{tikz_plot_matrix(df2matrix(pair_layout))}}
\end{center}





\end{document}