\documentclass{article}


\usepackage[portrait, headheight = 0cm, margin=0.25cm, top = 0.25cm, nofoot]{geometry} 
\usepackage[export]{adjustbox} 
\usepackage{graphicx}
\usepackage[dvipsnames,table]{xcolor} % [dvipsnames,table] for setting colors \usepackage{amsmath} \usepackage{xfrac}
\usepackage{xfrac}

\usepackage{tikz}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{shapes.misc}
\usetikzlibrary{external}
%\tikzexternalize[prefix=tikz-figures/] % activate!

\renewcommand{\familydefault}{\sfdefault} % sans serif

\begin{document}

<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
PROJECT_DIRECTORY<-"H:/equity_one_pager/" # keep updated
require(Hmisc)
require(Rtsne)
require(digest)
require(stringi)
require(readxl)
require(scales)
require(data.table)
require(Matrix)
require(Matrix.utils)
require(clue)
require(magick)
source("utility_functions.R")
source("sheet_utility_functions.R")
source("latex_helpers_v2.R")

df<-data.table(x=paste0("x",1:73),y=paste0("y",1:73),z=paste0("z",1:73))
side_by_side_count<-3
lines_per_page_count<-20
@


\Sexpr{make_df_layout(df,side_by_side_count=side_by_side_count,lines_per_page_count=lines_per_page_count)}

\end{document}