\documentclass{article}


\usepackage[portrait, headheight = 0cm, margin=0.25cm, top = 0.25cm, nofoot]{geometry} 
\usepackage[export]{adjustbox} 
\usepackage{graphicx}
\usepackage[dvipsnames,table]{xcolor} % [dvipsnames,table] for setting colors \usepackage{amsmath} \usepackage{xfrac}
\usepackage{xfrac}

\usepackage{tikz}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{shapes.misc}
\usetikzlibrary{external}
%\tikzexternalize[prefix=tikz-figures/] % activate!

\renewcommand{\familydefault}{\sfdefault} % sans serif

\begin{document}

<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
PROJECT_DIRECTORY<-"H:/equity_one_pager/" # keep updated
require(Hmisc)
require(Rtsne)
require(digest)
require(stringi)
require(readxl)
require(scales)
require(data.table)
require(Matrix)
require(Matrix.utils)
require(clue)
require(magick)
source("utility_functions.R")
source("sheet_utility_functions.R")
source("latex_helpers_v2.R")

m0<-matrix(1:100,ncol=10)

df0<-data.table(
  x=as.integer(row(m0)),
  y=as.integer(col(m0)),
  text=as.character(m0)
)

tkz0<-tikz_plot_nodes(df0,units="cm")

m1<-df2matrix(df0,col_slack = 0,row_slack = 0)

tkz1<-tikz_plot_matrix(content=m1,node="",content_size_factor=0.9)
#\includegraphics[height=3cm,width=3cm,valign=T]{H:/latex_utils/actual_data/tikz-figures/AC95.pdf}

@

\definecolor{FWY}{HTML}{FF0000}
\definecolor{GJN}{HTML}{FF9900}
\definecolor{KA}{HTML}{CCFF00}
\definecolor{MRX}{HTML}{33FF00}
\definecolor{PM}{HTML}{00FF66}
\definecolor{QBE}{HTML}{00FFFF}
\definecolor{QD}{HTML}{0066FF}
\definecolor{RJ}{HTML}{3300FF}
\definecolor{UX}{HTML}{CC00FF}
\definecolor{WI}{HTML}{FF0099}

\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{FWY!20}{FWY}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{GJN!20}{GJN}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{KA!20}{KA}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{MRX!20}{MRX}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{PM!20}{PM}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{QBE!20}{QBE}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{QD!20}{QD}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{RJ!20}{RJ}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{UX!20}{UX}}}};}
\hskip 2mm
\tikz{\path (0,0) node[draw,inner sep=1pt,outer sep=0pt]{
\resizebox*{2cm}{2cm}{{\setlength{\fboxsep}{0pt}\colorbox{WI!20}{WI}}}};}


\end{document}

