\documentclass{article}


\usepackage[portrait, headheight = 0cm, margin=0.25cm, top = 0.25cm, nofoot]{geometry} 
\usepackage[export]{adjustbox} 
\usepackage{graphicx}
\usepackage[dvipsnames,table]{xcolor} % [dvipsnames,table] for setting colors \usepackage{amsmath} \usepackage{xfrac}
\usepackage{xfrac}

\usepackage{tikz}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{shapes.misc}
\usetikzlibrary{external}
%\tikzexternalize[prefix=tikz-figures/] % activate!

\renewcommand{\familydefault}{\sfdefault} % sans serif

\begin{document}

<<, cache=FALSE, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results="hide">>=
PROJECT_DIRECTORY<-"H:/equity_one_pager/" # keep updated
require(Hmisc)
require(Rtsne)
require(digest)
require(stringi)
require(readxl)
require(scales)
require(data.table)
require(Matrix)
require(Matrix.utils)
require(clue)
require(magick)
source("utility_functions.R")
source("sheet_utility_functions.R")
source("latex_helpers_v2.R")

m0<-matrix(1:100,ncol=10)

df0<-data.table(
  x=as.integer(row(m0)),
  y=as.integer(col(m0)),
  text=as.character(m0)
)

tkz0<-tikz_plot_nodes(df0,units="cm")

m1<-df2matrix(df0,col_slack = 0,row_slack = 0)

tkz1<-tikz_plot_matrix(content=m1,node="",content_size_factor=0.9)
#\includegraphics[height=3cm,width=3cm,valign=T]{H:/latex_utils/actual_data/tikz-figures/AC95.pdf}

@

\definecolor{ABC}{HTML}{FF0000}
\definecolor{AC}{HTML}{FFDB00}
\definecolor{DH}{HTML}{49FF00}
\definecolor{GJ}{HTML}{00FF92}
\definecolor{IB}{HTML}{0092FF}
\definecolor{MC}{HTML}{4900FF}
\definecolor{RW}{HTML}{FF00DB}



\fbox{\resizebox{6mm}{7.714286mm}{ {\setlength{\fboxsep}{0pt}\colorbox{MC!20}{\bf\tiny MC114 }} }}
\fbox{\resizebox{6mm}{7.714286mm}{\adjustbox{cframe=MC!20}{MC114}}}
\fbox{\resizebox{6mm}{7.714286mm}{ \includegraphics{H:/latex_utils/actual_data/tikz-figures/AC95.pdf}}}
\fbox{\resizebox{6mm}{7.714286mm}{{\bf\tiny MC114 }}}

\end{document}

